version: 2
jobs:
  build:
    working_directory: ~/react-tour-of-heroes
    docker:
      - circleci/node:6.9.1
    steps:
      - checkout
      - run:
          name: install all dependencies
          command: npm install -g firebase-tools
          command: npm install -g create-react-app
          command: npm install -g codecov 
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install 
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    working_directory: ~/react-tour-of-heroes
    steps:
      - run:
          name: Running tests
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

    
