defaults: &defaults
  docker:
      - image: circleci/node:6.14

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run: ls -lah
      - run: pwd
      - run: cp -a /home/circleci/project/. /tmp/workspace/
      - run: ls -lah /tmp/workspace
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install 
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: tmp
          paths:
            - workspace
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install tests dependencies
          command: sudo npm install -g codecov 
      - run:
          name: Running tests
          command: CI=true npm test -- --coverage && codecov
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/workspace
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install deploy dependencies
          command: sudo npm install -g firebase-tools
      - run:
          name: Running build
          command: CI=true npm run build
      - run:
          name: Deploy into firebase
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
      
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - approve:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - approve



    
