version: 2
jobs:
  build:
    working_directory: ~/react-tour-of-heroes
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install 
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    working_directory: ~/react-tour-of-heroes
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install tests dependencies
          command: sudo npm install -g codecov 
      - run:
          name: Running tests
          command: CI=true npm test -- --coverage && codecov
    deploy:
      working_directory: ~/react-tour-of-heroes
      docker:
        - image: circleci/node:6
      steps:
        - checkout
        - restore_cache: # special step to restore the dependency cache 
            key: dependency-cache-{{ checksum "package.json" }}
        - run:
            name: install deploy dependencies
            command: npm install -g firebase-tools
        - run:
            name: Running build
            command: CI=true npm run build
        - run:
            name: Deploy into firebase
            command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - approve:
        type: approval
        requires:
          - test
      - deploy:
          requires:
            - aprrove


    
